# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
# 忽略 cocoapods 中的警告
inhibit_all_warnings!

target 'Cicada' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cicada
  pod 'AFNetworking', '~> 4.0.1'
  pod 'SDWebImage', '~> 5.9.5'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'MJRefresh', '~> 3.5.0'
  pod 'FMDB', '~> 2.7.5'
  pod 'YYKit', '~> 1.0.9'
  pod 'pop', '~> 1.0.12'

  target 'CicadaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CicadaUITests' do
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
    end
end
